services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ares_software
      POSTGRES_USER: user_ares2025
      POSTGRES_PASSWORD: ares*2025
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:Z

volumes:
  db_data:
